import enum
import uuid
from datetime import datetime

from sqlalchemy import Column, String, DateTime, Text, ForeignKey, Enum, Boolean, Float
from sqlalchemy.dialects.postgresql import UUID

from app.database import Base


class ComplianceStatus(str, enum.Enum):
    COMPLIANT = "compliant"
    NON_COMPLIANT = "non_compliant"
    NEEDS_REVIEW = "needs_review"


class RiskLevel(str, enum.Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class ComplianceResult(Base):
    """
    One row per (tender, bidder) — the latest compliance evaluation. Re-running
    the engine (POST /api/compliance/bidder/{id}/evaluate) overwrites this row
    in place so there is always exactly one current verdict per bidder.

    `requirement_results` holds the full per-requirement breakdown (the list of
    objects described in the Day-4 spec: requirement/required_value/actual_value/
    status/reason/evidence/source_document/...) serialized as JSON, since the
    field set is inherently a variable-length list, not a fixed set of columns.
    """
    __tablename__ = "compliance_results"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tender_id = Column(UUID(as_uuid=True), ForeignKey("tenders.id"), nullable=False)
    bidder_id = Column(UUID(as_uuid=True), ForeignKey("bidders.id"), nullable=False, unique=True)

    overall_status = Column(Enum(ComplianceStatus), default=ComplianceStatus.NEEDS_REVIEW)
    risk_level = Column(Enum(RiskLevel), default=RiskLevel.MEDIUM, nullable=False)

    compliance_score = Column(Float, default=0.0, nullable=False)   # 0-100, compliant_count / total * 100
    mandatory_failed = Column(Boolean, default=False, nullable=False)

    explanation = Column(Text, nullable=True)
    requirement_results = Column(Text, nullable=True)  # JSON array, see compliance_engine.py

    # --- Day 6: AI Recommendation Engine ---
    # 2-3 line human-readable recommendation generated by ai_service after the
    # deterministic verdict above is already final. Purely narrative - never
    # feeds back into overall_status/compliance_score/risk_level.
    ai_recommendation = Column(Text, nullable=True)
    ai_recommendation_generated_at = Column(DateTime, nullable=True)

    # --- Upgrade: Explainable compliance ---
    # JSON array of structured requirement results with reason_codes and evidence chains
    # Replaces/extends the existing requirement_results field format
    evidence_chain = Column(Text, nullable=True)    # JSON: full evidence chain per requirement
    risk_breakdown = Column(Text, nullable=True)    # JSON: {compliance_failures, gov_mismatches, ...}

    total_requirements = Column(String(10), default="0")
    compliant_count = Column(String(10), default="0")
    non_compliant_count = Column(String(10), default="0")
    needs_review_count = Column(String(10), default="0")

    evaluated_by = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    evaluated_at = Column(DateTime, default=datetime.utcnow)
